#服务名称
#服务端口
server:
  port: 8761
##默认eureka-server  服务注册中心会把自己当做客户端尝试注册它自己，所以我们禁止他的客户端行为
#eureka:
#  client:
#    register-with-eureka: false                  #默认为true
#    fetch-registry: false                         #默认为true
#    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/     #注册中心     http://${spring.application.name}:${server.port}/eureka/


#开启rureka进行身份校验
#开启身份校验，需要引入 spring-security 的依赖
     #注册中心     http://user:password@${spring.application.name}:${server.port}/eureka/
eureka:
  instance:
    hostamne: localhost
  client:
    # ureka-Server 会启动一个 Eureka-Client 客户端，用于 Eureka-Server 集群之间的请求交互，因为这里我们仅仅搭建 Eureka-Server 单节点，所以设置 register-with-eureka 和 fetch-registry 配置项为 false，无需相互注册。
    register-with-eureka: false                  #不注册到 Eureka-Server,默认为true
    fetch-registry: false                         # 不从 Eureka-Server 获取注册表，默认为true
    serviceUrl:
      #defaultZone:  http://username:password@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://username:password@loaclhost:8761/eureka/
  server:
  # 关闭eureka的自我保护机制
  #EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.
    enable-self-preservation: false

#开启认证
security:
  basic:
    enabled: true
  user:
    #账号
    name: gengzi
    #密码
    password: gengzi



