#实现eureka 注册中心的高可用,搭建多个节点的eureka注册中心
# 需要将本项目打包 jar  执行命令： java -jar gengzi-eureka-server-1.0-SNAPSHOT.jar --spring.profiles.active=peer1   启动 ，每个节点都需要启动
spring:
  application:
    name: eureka-server
server:
  port: 8762        #不同节点端口不同

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://gengzi:gengzi@peer2:8763/eureka/,http://gengzi:gengzi@peer3:8764/eureka/     #将本服务注册中心注册到其他节点上
  instance:
    hostname: peer1   #不同节点的主机名
#开启认证
security:
  user:
    name: gengzi
    password: gengzi
  basic:
    enabled: true





