server:
  port: 8303
spring:
  application:
    name: rabbitmq-hello
    # 连接rabbitmq 的服务器
  rabbitmq:
    host: localhost
    port: 5672
    username: gengzi
    password: gengzi
    virtual-host: /

# mq 的设置
mq:
  # queue 配置
  queue:
    durable: true
    exclusive: false
    autoDelete: false
    name: email_queue
  exchange:
    name: email_exchange
    durable: true
    autoDelete: false
  routekey:
    name: email_routekey


