#服务名称
#服务端口
server:
  port: 5001
spring:
  application:
    name: config-server
  # 配置git配置中心
  cloud:
    config:
      server:
        git:
        #配置git仓库的位置
          uri: https://github.com/gengzi/springcloud.git
          # 配置仓库路径下的相对搜索路径，可以配置多个
          searchPaths: config-repo
          username: 1164014750@qq.com
          password: songmengke521..

#uri 如果想以本地仓库运行，可以设置
#  cloud:
#    config:
#      server:
#        git:
#        #配置git仓库的位置
#          uri: file://${user.home}/config-repo         ${user.home} 代表当前用户所述目录


